version: '3.8'

services:
  docker-drop:
    build: .
    container_name: nerwander/docker-drop:latest
    ports:
      - "5082:5000"
    volumes:
      - /data/Drop:/output
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
